// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQCHKadPQPOsCIBH2zSw8bKZCLvo-UcGQ',
    appId: '1:881187643270:web:a25fe6c9ddd7430e45d607',
    messagingSenderId: '881187643270',
    projectId: 'quotes-app-b68c3',
    authDomain: 'quotes-app-b68c3.firebaseapp.com',
    storageBucket: 'quotes-app-b68c3.firebasestorage.app',
    measurementId: 'G-HE9Z2ETQMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3scFp3v9P1g9nohWYr79L-72POpwdRhQ',
    appId: '1:881187643270:android:d3207497a8db18a745d607',
    messagingSenderId: '881187643270',
    projectId: 'quotes-app-b68c3',
    storageBucket: 'quotes-app-b68c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0oPFPpDBEAgNfk_8sTMfbUzt1xtJb3-A',
    appId: '1:881187643270:ios:f13e7488c273bd0845d607',
    messagingSenderId: '881187643270',
    projectId: 'quotes-app-b68c3',
    storageBucket: 'quotes-app-b68c3.firebasestorage.app',
    iosBundleId: 'com.example.quotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0oPFPpDBEAgNfk_8sTMfbUzt1xtJb3-A',
    appId: '1:881187643270:ios:f13e7488c273bd0845d607',
    messagingSenderId: '881187643270',
    projectId: 'quotes-app-b68c3',
    storageBucket: 'quotes-app-b68c3.firebasestorage.app',
    iosBundleId: 'com.example.quotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQCHKadPQPOsCIBH2zSw8bKZCLvo-UcGQ',
    appId: '1:881187643270:web:59ea9eb78fae9cd445d607',
    messagingSenderId: '881187643270',
    projectId: 'quotes-app-b68c3',
    authDomain: 'quotes-app-b68c3.firebaseapp.com',
    storageBucket: 'quotes-app-b68c3.firebasestorage.app',
    measurementId: 'G-4FX0BZCHDD',
  );
}
